name: Bug Report
description: If you come across a bug while using the Discord bot, please use the following template to report it and help us improve the bot.
labels: ['unconfirmed bug']
assignees: []
body:
    - type: markdown
      id: message
      attributes:
          value: Thanks for taking the time to fill out this bug report!
    - type: checkboxes
      id: preflight-checklist
      attributes:
          label: Preflight Checklist
          description: Please ensure you've completed all of the following.
          options:
              - label: I have read and agree to follow the [code of conduct](https://github.com/paperback-community/discord-bot?tab=coc-ov-file#readme).
                required: true
              - label: I have read and agree to follow the [support disclaimer](https://github.com/paperback-community/discord-bot/blob/master/.github/SUPPORT.md).
                required: true
              - label: I experienced this bug on the latest stable or development version of the Discord bot.
                required: true
              - label: I have searched the [issue tracker](https://github.com/paperback-community/discord-bot/issues) for a bug report that matches the one I want to file, without success.
                required: true
    - type: input
      id: device-os
      attributes:
          label: Operating System Type(s) and Version(s)
          description: What operating system type(s) version(s) have you encountered the bug with?
          placeholder: 'e.g. Debian bookworm 12.7, Windows 11 Pro version 24H2 or macOS Sequoia 15.0'
      validations:
          required: true
    - type: input
      id: device-chipset
      attributes:
          label: Device Chipset(s)
          description: What chipset(s) have you encountered the bug with?
          placeholder: 'e.g., x86 (Intel, AMD) or ARM (Apple M series, Qualcomm Snapdragon)'
      validations:
          required: true
    - type: textarea
      id: bug-description
      attributes:
          label: Describe the Bug
          description: A clear and concise description of the bug that you encountered and what you expected to actually happen.
          placeholder: Tell us about the bug!
      validations:
          required: true
    - type: textarea
      id: bug-replication
      attributes:
          label: Steps to Reproduce
          description: Tell us how you triggered the bug so we can try to reproduce it ourselves.
          placeholder: 1. ...
      validations:
          required: true
    - type: textarea
      id: extra-info
      attributes:
          label: Anything Else?
          description: |
              Images, logs or links? Anything that will give us more context about the bug which you are encountering!

              Tip: You can attach images, logs files or any other file by clicking this area to highlight it and then dragging files in.
          placeholder: Images, logs, links, ...
      validations:
          required: false
